SENDER_MAIL = "ENTER EMAIL HERE"
SENDER_MAIL_PASSWORD = "ENTER PASSWORD HERE"
API_KEY = "ENTER API KEY"
MYSQL_PASSWORD = "ENTER MYSQL PASSWORD HERE"
SMTP_SERVER = 'Use your SMTP server'
SMTP_PORT = 'ENter SMPT port in number'